nextflow-run:
	nextflow run tutorial.nf -with-trace -with-timeline -with-dag -with-report

nextflow-cleanup: 
	rm -rf .nextflow* docker.dot* docker.html* work dag.dot* report.html* timeline.html* trace.txt*
