apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-
spec:
  entrypoint: workflow-template
  arguments:
    parameters:
    - name: workflow-input
      value: |
        {"msg": "activator run"}

  templates:
  - name: workflow-template
    steps:
    - - name: activator
        template: activator-template
        arguments:
          parameters:
          - name: activator-input
            value: "{{workflow.parameters.workflow-input}}"
        
    - - name: processor
        template: processor-template
        arguments:
          artifacts:
          - name: processor-input
            from: "{{steps.activator.outputs.artifacts.activator-output}}"

  - name: activator-template
    inputs:
      parameters:
      - name: activator-input
    container:
      image: nasa-hsi-argo
      imagePullPolicy: Never
      command: [python, /workdir/activator.py]
      args: ["{{inputs.parameters.activator-input}}"]
    outputs:
      artifacts:
      - name: activator-output
        path: /workdir/activator_event.json

  - name: processor-template
    inputs:
      artifacts:
      - name: processor-input
        path: /tmp/processor_event.json
    container:
      image: nasa-hsi-argo
      imagePullPolicy: Never
      command: [python, /workdir/processor.py]
      args: ["{{inputs.artifacts.processor-input.path}}"]
    outputs:
      artifacts:
      - name: processor-output
        path: /workdir/processor_event.json
